### ISSUE TITLE
Modify QCloud API  Agendo User

### ISSUE THREAD

**Issue by rolivella** [proteomicsunitcrg/qsample-server#77]
Here: https://github.com/proteomicsunitcrg/qcloud2-api/blob/cf3bfed04377efce1a48217d6b8599bb516d26b0/config_sample.yaml#L38

At QCloud VM, `/home/admin/qcloud2-api/ config.yaml`:

``` yaml
qsample:
  user: qsample
  password: qsample
  agendoUser: marc.serret@crg.eu
```
